##
## Build with Travis.CI
##
language: r
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel
after_script:
  - |
    R -e 'if(require("plotteR")) { remove.packages("plotteR"); }; r <- devtools::install_github("thomasWeise/plotteR"); if(r) { cat("OK\n"); q(save="no", status=0); } else { cat("error: ", r, "\n", sep="", collapse=""); q(save="no", status=1); }'

